# This is a Docker Compose file
# Sample usage: docker compose up -d

volumes:
  minio-vol:
  neo4j-vol:
  main-app-vol:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind

services:
  server:
    image: node
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: "npm run dev"
    restart: always

    ports:
      - published: 5501
        target: 5501

    volumes:
    - type: volume
      source: main-app-vol
      target: /usr/src/app

  minio:
    image: minio/minio
    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

    environment:
      - MINIO_ROOT_USER=myminioadmin
      - MINIO_ROOT_PASSWORD=myminioadmin

    command: minio server /data --console-address ":9001"

    ports:
      - published: 9000
        target: 9000
      - published: 9001
        target: 9001

    volumes:
    - type: volume
      source: minio-vol
      target: /data

  neo4j:
    image: neo4j
    restart: always
    
    environment:
    - NEO4J_AUTH=none
    - NEO4J_PLUGINS=["apoc","graph-data-science"]

    ports:
    - published: 7474
      target: 7474
    - published: 7687
      target: 7687
    
    volumes:
    - type: volume
      source: neo4j-vol
      target: /data
