# This is a Docker Compose file
# Sample usage: docker compose up -d

volumes:
  bim-app-vol:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind

services:
  server:
    image: node
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: "npm run dev"
    restart: always

    ports:
      - published: 5501
        target: 5501

    volumes:
    - type: volume
      source: bim-app-vol
      target: /usr/src/app
